#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JumbotronGame.AndroidApp.Resource", IsApplication=true)]

namespace JumbotronGame.AndroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arenaevent = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int prospera_place = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int save_on_foods = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int ArenaEventsListContainer = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int DateTextView = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int HeaderTextView = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int LoadingProgress = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int PreviewImage = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int QuizAnswerA = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int QuizAnswerB = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int QuizAnswerC = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int QuizAnswerD = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int QuizContainer = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int QuizQuestion = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int UserProfile_Container = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int UserProfile_fullName = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int UserProfile_points = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int actionBar = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int action_userprofile = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int space1 = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ArenaEventListItemTemplate = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ArenaEventTemplate = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int QuizBeginFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int QuizCompletedFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int QuizFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int UserProfileTemplate = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int options_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int arena_events_header = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int quiz_completed = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int userprofile = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int userprofile_FullName = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int userprofile_Points = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyCustomTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
